# Generated by Django 5.1.6 on 2025-03-07 17:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0003_alter_listings_image_watchlist"),
    ]

    operations = [
        migrations.AddField(
            model_name="comments",
            name="datetime",
            field=models.DateTimeField(
                auto_now_add=True,
                db_default=datetime.datetime(2025, 3, 7, 17, 21, 17, 140041),
            ),
        ),
        migrations.AddField(
            model_name="listings",
            name="datetime",
            field=models.DateTimeField(
                auto_now_add=True,
                db_default=datetime.datetime(2025, 3, 7, 17, 21, 17, 139351),
            ),
        ),
    ]
