# Generated by Django 5.1.6 on 2025-03-09 18:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0004_comments_datetime_listings_datetime"),
    ]

    operations = [
        migrations.AddField(
            model_name="listings",
            name="closed",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="comments",
            name="datetime",
            field=models.DateTimeField(
                auto_now_add=True,
                db_default=datetime.datetime(2025, 3, 9, 18, 4, 53, 125461),
            ),
        ),
        migrations.AlterField(
            model_name="listings",
            name="datetime",
            field=models.DateTimeField(
                auto_now_add=True,
                db_default=datetime.datetime(2025, 3, 9, 18, 4, 53, 124755),
            ),
        ),
    ]
