# Generated by Django 5.1.6 on 2025-03-14 00:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0005_listings_closed_alter_comments_datetime_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="listings",
            name="closed",
        ),
        migrations.AddField(
            model_name="listings",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="comments",
            name="datetime",
            field=models.DateTimeField(
                auto_now_add=True,
                db_default=datetime.datetime(2025, 3, 14, 0, 29, 24, 94827),
            ),
        ),
        migrations.AlterField(
            model_name="listings",
            name="datetime",
            field=models.DateTimeField(
                auto_now_add=True,
                db_default=datetime.datetime(2025, 3, 14, 0, 29, 24, 93739),
            ),
        ),
    ]
