# Generated by Django 5.1.6 on 2025-03-15 14:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0006_remove_listings_closed_listings_active_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comments",
            old_name="comment",
            new_name="content",
        ),
        migrations.AlterField(
            model_name="comments",
            name="datetime",
            field=models.DateTimeField(
                auto_now_add=True,
                db_default=datetime.datetime(2025, 3, 15, 14, 16, 14, 702368),
            ),
        ),
        migrations.AlterField(
            model_name="listings",
            name="datetime",
            field=models.DateTimeField(
                auto_now_add=True,
                db_default=datetime.datetime(2025, 3, 15, 14, 16, 14, 701649),
            ),
        ),
    ]
