# Generated by Django 5.1.6 on 2025-03-15 14:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0007_rename_comment_comments_content_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="listings",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    (0, "Electronics"),
                    (1, "Fashion"),
                    (2, "Home"),
                    (3, "Study"),
                    (4, "Toys"),
                ],
                max_length=18,
            ),
        ),
        migrations.AlterField(
            model_name="comments",
            name="datetime",
            field=models.DateTimeField(
                auto_now_add=True,
                db_default=datetime.datetime(2025, 3, 15, 14, 41, 0, 695102),
            ),
        ),
        migrations.AlterField(
            model_name="listings",
            name="datetime",
            field=models.DateTimeField(
                auto_now_add=True,
                db_default=datetime.datetime(2025, 3, 15, 14, 41, 0, 694119),
            ),
        ),
    ]
