# Generated by Django 5.1.6 on 2025-03-15 22:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0014_alter_comments_datetime_alter_listings_category_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="listings",
            name="category",
        ),
        migrations.AlterField(
            model_name="comments",
            name="datetime",
            field=models.DateTimeField(
                auto_now_add=True,
                db_default=datetime.datetime(2025, 3, 15, 22, 44, 6, 278670),
            ),
        ),
        migrations.AlterField(
            model_name="listings",
            name="datetime",
            field=models.DateTimeField(
                auto_now_add=True,
                db_default=datetime.datetime(2025, 3, 15, 22, 44, 6, 277956),
            ),
        ),
    ]
