# Generated by Django 5.1.6 on 2025-03-15 23:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0017_alter_comments_datetime_alter_listings_datetime"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("Electronics", "Electronics"),
                            ("Fashion", "Fashion"),
                            ("Home", "Home"),
                            ("Toys", "Toys"),
                        ],
                        max_length=25,
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="comments",
            name="datetime",
            field=models.DateTimeField(
                auto_now_add=True,
                db_default=datetime.datetime(2025, 3, 15, 23, 9, 54, 297604),
            ),
        ),
        migrations.AlterField(
            model_name="listings",
            name="datetime",
            field=models.DateTimeField(
                auto_now_add=True,
                db_default=datetime.datetime(2025, 3, 15, 23, 9, 54, 296535),
            ),
        ),
    ]
