# Generated by Django 5.1.6 on 2025-03-15 23:12

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0018_category_alter_comments_datetime_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="listings",
            name="category",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="auctions.category",
            ),
        ),
        migrations.AlterField(
            model_name="comments",
            name="datetime",
            field=models.DateTimeField(
                auto_now_add=True,
                db_default=datetime.datetime(2025, 3, 15, 23, 12, 37, 668701),
            ),
        ),
        migrations.AlterField(
            model_name="listings",
            name="datetime",
            field=models.DateTimeField(
                auto_now_add=True,
                db_default=datetime.datetime(2025, 3, 15, 23, 12, 37, 667957),
            ),
        ),
    ]
